version: '3'
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: my-example
    volumes:
      - ./wp-content:/var/www/html/wp-content
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: my-example
      MYSQL_DATABASE: wordpress
